package run

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// continueFixture is the shared scaffolding the continue tests use: a
// fresh aiEnvDir plus a helper to drop a previous run with a chosen
// terminal state. Each test builds its own previous run so the test
// cases stay independent.
type continueFixture struct {
	aiEnvDir string
	envName  string
	now      time.Time
}

// newContinueFixture returns a fixture with a temp aiEnvDir and a
// fixed env name. The "now" timestamp is one minute after the previous
// run's clock so the new run sorts after it lexically (run IDs are
// generated by GenerateRunID; the fixture's CreatePrev uses a fixed
// run ID so order is deterministic regardless).
func newContinueFixture(t *testing.T) continueFixture {
	t.Helper()
	return continueFixture{
		aiEnvDir: filepath.Join(t.TempDir(), ".ai-env"),
		envName:  "fix-tests",
		now:      time.Date(2026, 5, 28, 10, 30, 0, 0, time.UTC),
	}
}

// createPrevRun materializes a previous run directory under the
// fixture's aiEnvDir with the given run ID, state, and task. It writes
// the run.json snapshot directly (no supervisor) so the test pins the
// exact terminal the gate observes.
//
// runID must be lexically less than any subsequent GenerateRunID output
// so the new run sorts after it; tests pass an explicit fixed ID
// ("20260528-101000-aaaaaa" by default) to make this deterministic.
func (f continueFixture) createPrevRun(t *testing.T, runID string, state State, task string) RunDirectory {
	t.Helper()
	createdAt := time.Date(2026, 5, 28, 10, 10, 0, 0, time.UTC)
	dir, err := CreateRunDirectory(f.aiEnvDir, runID, createdAt)
	if err != nil {
		t.Fatalf("CreateRunDirectory: %v", err)
	}
	if task != "" {
		if err := WriteTask(f.aiEnvDir, runID, task); err != nil {
			t.Fatalf("WriteTask: %v", err)
		}
	}
	rec := Record{
		RunID:               runID,
		EnvName:             f.envName,
		Agent:               "claude",
		Task:                task,
		State:               state,
		Backend:             "local-process",
		ModelCredentialMode: ModelCredentialBackendManaged,
	}
	// Populate stop fields when the state is terminal so the record
	// looks like a real supervisor's closing snapshot.
	if state.IsTerminal() {
		stopped := createdAt.Add(5 * time.Minute)
		rec.StoppedAt = &stopped
		reason := StopReasonForState(state)
		if reason != "" {
			rec.StopReason = &reason
		}
		started := createdAt
		rec.StartedAt = &started
	}
	if err := WriteRecord(dir.Path, rec); err != nil {
		t.Fatalf("WriteRecord: %v", err)
	}
	return dir
}

// TestPrepareContinuation_ReusesWorkspaceAndLinks verifies the happy
// path: a previous run that ended in StateKilledByUser is continuable;
// PrepareContinuation creates a NEW run directory next to it, the
// returned Continuation carries the prior run's ID for the supervisor
// to thread into run.json's linked_previous_run, and the previous
// run's directory + the workspace tree are left exactly as they were
// (no checkout, no reset, no clean).
func TestPrepareContinuation_ReusesWorkspaceAndLinks(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-aaaaaa"
	prevTask := "Resume the failing tests"
	prev := fx.createPrevRun(t, prevID, StateKilledByUser, prevTask)

	// Sentinel files in the (fake) workspace tree so we can prove they
	// survive the continuation. The continuation must not delete or
	// recreate anything under .ai-env/workspaces/<env>/.
	wsRoot := filepath.Join(fx.aiEnvDir, "workspaces", fx.envName)
	if err := os.MkdirAll(wsRoot, 0o755); err != nil {
		t.Fatalf("MkdirAll workspace: %v", err)
	}
	sentinel := filepath.Join(wsRoot, "agent-progress.txt")
	if err := os.WriteFile(sentinel, []byte("agent-was-here"), 0o644); err != nil {
		t.Fatalf("write sentinel: %v", err)
	}

	cont, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
	if err != nil {
		t.Fatalf("PrepareContinuation: %v", err)
	}

	if cont.PreviousRunID != prevID {
		t.Errorf("PreviousRunID = %q, want %q", cont.PreviousRunID, prevID)
	}
	if cont.NewRun.ID == prevID {
		t.Errorf("NewRun.ID = %q, want a fresh id distinct from %q", cont.NewRun.ID, prevID)
	}
	if cont.NewRun.Path == prev.Path {
		t.Errorf("NewRun.Path = %q, expected a sibling of the previous run", cont.NewRun.Path)
	}
	if got := filepath.Dir(cont.NewRun.Path); got != filepath.Dir(prev.Path) {
		t.Errorf("NewRun parent = %q, want sibling of previous parent %q", got, filepath.Dir(prev.Path))
	}

	// The previous run directory and its run.json must be untouched.
	if _, err := os.Stat(prev.Path); err != nil {
		t.Errorf("previous run dir missing: %v", err)
	}
	prevAfter, err := ReadRecord(prev.Path)
	if err != nil {
		t.Fatalf("ReadRecord(prev): %v", err)
	}
	if prevAfter.State != StateKilledByUser {
		t.Errorf("previous run state changed: %q", prevAfter.State)
	}

	// The workspace sentinel must still exist with the same content.
	got, err := os.ReadFile(sentinel)
	if err != nil {
		t.Fatalf("read sentinel after continuation: %v", err)
	}
	if string(got) != "agent-was-here" {
		t.Errorf("sentinel content = %q, want preserved", string(got))
	}

	// The new run's task.md must mirror the previous run's task body
	// because we did not supply a fresh --task.
	if cont.TaskSource != TaskSourceInherited {
		t.Errorf("TaskSource = %q, want %q", cont.TaskSource, TaskSourceInherited)
	}
	newTaskBytes, err := os.ReadFile(TaskPath(fx.aiEnvDir, cont.NewRun.ID))
	if err != nil {
		t.Fatalf("read new task.md: %v", err)
	}
	if !strings.Contains(string(newTaskBytes), prevTask) {
		t.Errorf("new task.md = %q, want to contain previous task %q", string(newTaskBytes), prevTask)
	}

	// The LinkedPreviousRunPtr helper must convert PreviousRunID to a
	// pointer the supervisor can thread straight into run.json.
	ptr := LinkedPreviousRunPtr(cont.PreviousRunID)
	if ptr == nil || *ptr != prevID {
		t.Errorf("LinkedPreviousRunPtr = %v, want pointer to %q", ptr, prevID)
	}
}

// TestPrepareContinuation_FreshTaskOverridesInherited verifies the
// `--task` override path: when the operator supplies a non-empty task,
// the new run's task.md contains the new text and the prior task body
// is NOT propagated. TaskSource reports "fresh" so the CLI summary can
// surface the override.
func TestPrepareContinuation_FreshTaskOverridesInherited(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-bbbbbb"
	prevTask := "Old task body"
	freshTask := "Try a different approach to the failing tests"
	_ = fx.createPrevRun(t, prevID, StateTimedOut, prevTask)

	cont, err := PrepareContinuation(fx.aiEnvDir, fx.envName, freshTask, fx.now)
	if err != nil {
		t.Fatalf("PrepareContinuation: %v", err)
	}
	if cont.TaskSource != TaskSourceFresh {
		t.Errorf("TaskSource = %q, want %q", cont.TaskSource, TaskSourceFresh)
	}
	taskBytes, err := os.ReadFile(TaskPath(fx.aiEnvDir, cont.NewRun.ID))
	if err != nil {
		t.Fatalf("read new task.md: %v", err)
	}
	body := string(taskBytes)
	if !strings.Contains(body, freshTask) {
		t.Errorf("new task.md = %q, want to contain fresh task %q", body, freshTask)
	}
	if strings.Contains(body, prevTask) {
		t.Errorf("new task.md = %q, must not contain previous task %q", body, prevTask)
	}
}

// TestPrepareContinuation_NoPreviousRunErrors asserts the "no runs to
// continue" failure path: when the env has never been run, the helper
// returns a *ContinueError of kind ContinueErrNoPreviousRun and does
// NOT create any new run directory (so a retry is clean).
func TestPrepareContinuation_NoPreviousRunErrors(t *testing.T) {
	fx := newContinueFixture(t)

	_, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "any task", fx.now)
	if err == nil {
		t.Fatalf("PrepareContinuation: expected error, got nil")
	}
	var ce *ContinueError
	if !errors.As(err, &ce) {
		t.Fatalf("error type = %T, want *ContinueError: %v", err, err)
	}
	if ce.Kind != ContinueErrNoPreviousRun {
		t.Errorf("ContinueError.Kind = %v, want %v", ce.Kind, ContinueErrNoPreviousRun)
	}
	if !strings.Contains(ce.Error(), "no previous run") {
		t.Errorf("error message = %q, want substring 'no previous run'", ce.Error())
	}
	// No runs directory should have been created.
	if _, statErr := os.Stat(RunsRoot(fx.aiEnvDir)); statErr == nil {
		// The runs dir may have been created by something else in the
		// future; what matters is that no new run directory landed.
		entries, _ := os.ReadDir(RunsRoot(fx.aiEnvDir))
		if len(entries) != 0 {
			t.Errorf("runs dir non-empty after failed continuation: %v", entries)
		}
	}
}

// TestPrepareContinuation_PreviousRunActiveErrors asserts the
// "previous run still active" failure path: when the latest run is in
// a non-terminal state (e.g. StateRunning), the helper refuses with a
// ContinueErrPreviousRunActive error so the CLI does not race a live
// supervisor.
func TestPrepareContinuation_PreviousRunActiveErrors(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-cccccc"
	_ = fx.createPrevRun(t, prevID, StateRunning, "Currently running")

	_, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
	if err == nil {
		t.Fatalf("PrepareContinuation: expected error, got nil")
	}
	var ce *ContinueError
	if !errors.As(err, &ce) {
		t.Fatalf("error type = %T, want *ContinueError: %v", err, err)
	}
	if ce.Kind != ContinueErrPreviousRunActive {
		t.Errorf("ContinueError.Kind = %v, want %v", ce.Kind, ContinueErrPreviousRunActive)
	}
	if ce.PreviousID != prevID {
		t.Errorf("ContinueError.PreviousID = %q, want %q", ce.PreviousID, prevID)
	}
	if ce.PreviousState != StateRunning {
		t.Errorf("ContinueError.PreviousState = %q, want %q", ce.PreviousState, StateRunning)
	}
	if !strings.Contains(ce.Error(), "still active") {
		t.Errorf("error message = %q, want substring 'still active'", ce.Error())
	}
}

// TestPrepareContinuation_NonContinuableTerminalErrors walks the
// terminals the plan does NOT mark as continuable and asserts each
// surfaces a ContinueErrPreviousRunNotContinuable error. A clean
// StateCompleted, a StateFailedAgent, etc. all carry their own
// remediation paths; the user should not be hinted toward --continue
// for them.
func TestPrepareContinuation_NonContinuableTerminalErrors(t *testing.T) {
	cases := []State{
		StateCompleted,
		StateFailedAgent,
		StateFailedBackend,
		StateFailedPolicy,
		StateFailedScan,
		StateKilledOOM,
		StateQuarantined,
	}
	for _, state := range cases {
		state := state
		t.Run(string(state), func(t *testing.T) {
			fx := newContinueFixture(t)
			prevID := "20260528-101000-dddddd"
			_ = fx.createPrevRun(t, prevID, state, "Whatever")

			_, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
			if err == nil {
				t.Fatalf("PrepareContinuation(%q): expected error, got nil", state)
			}
			var ce *ContinueError
			if !errors.As(err, &ce) {
				t.Fatalf("error type = %T, want *ContinueError: %v", err, err)
			}
			if ce.Kind != ContinueErrPreviousRunNotContinuable {
				t.Errorf("ContinueError.Kind = %v, want %v (state=%q)", ce.Kind, ContinueErrPreviousRunNotContinuable, state)
			}
			if ce.PreviousState != state {
				t.Errorf("ContinueError.PreviousState = %q, want %q", ce.PreviousState, state)
			}
			if !strings.Contains(ce.Error(), "cannot be continued") {
				t.Errorf("error message = %q, want substring 'cannot be continued'", ce.Error())
			}
		})
	}
}

// TestPrepareContinuation_AllContinuableTerminalsAccepted is the
// positive twin of the non-continuable test: the three terminals the
// plan lists as continuable (killed_by_user, timed_out, killed_idle)
// must all succeed. Pins the gate against accidental tightening.
func TestPrepareContinuation_AllContinuableTerminalsAccepted(t *testing.T) {
	cases := []State{
		StateKilledByUser,
		StateTimedOut,
		StateKilledIdle,
	}
	for _, state := range cases {
		state := state
		t.Run(string(state), func(t *testing.T) {
			fx := newContinueFixture(t)
			prevID := "20260528-101000-eeeeee"
			_ = fx.createPrevRun(t, prevID, state, "Resume me")

			cont, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
			if err != nil {
				t.Fatalf("PrepareContinuation(%q): %v", state, err)
			}
			if cont.PreviousRunID != prevID {
				t.Errorf("PreviousRunID = %q, want %q", cont.PreviousRunID, prevID)
			}
			if cont.NewRun.ID == "" {
				t.Error("NewRun.ID is empty")
			}
		})
	}
}

// TestPrepareContinuation_MissingTaskInheritedFromPrev confirms that
// the inherited-task path uses the prior run's Record.Task verbatim,
// even when the user supplies whitespace-only --task content (which
// WriteTask rejects upstream). Whitespace-only is treated as "not
// supplied" because the trim semantics mirror WriteTask's contract.
func TestPrepareContinuation_MissingTaskInheritedFromPrev(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-ffffff"
	prevTask := "Original instruction"
	_ = fx.createPrevRun(t, prevID, StateKilledIdle, prevTask)

	cont, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "   \t\n", fx.now)
	if err != nil {
		t.Fatalf("PrepareContinuation: %v", err)
	}
	if cont.TaskSource != TaskSourceInherited {
		t.Errorf("TaskSource = %q, want %q", cont.TaskSource, TaskSourceInherited)
	}
	body, err := os.ReadFile(TaskPath(fx.aiEnvDir, cont.NewRun.ID))
	if err != nil {
		t.Fatalf("read new task.md: %v", err)
	}
	if !strings.Contains(string(body), prevTask) {
		t.Errorf("new task.md = %q, want to contain %q", string(body), prevTask)
	}
}

// TestPrepareContinuation_PreviousWithoutTaskRequiresFresh asserts the
// edge case where the previous run never recorded a task body (e.g. an
// older run.json written before WriteTask was wired, or a manual edit
// that cleared the field). PrepareContinuation must refuse to leave
// task.md empty and must surface a clear error so the operator
// supplies --task explicitly. The new run directory must be removed so
// a retry starts clean.
func TestPrepareContinuation_PreviousWithoutTaskRequiresFresh(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-aabbcc"
	// Use a state that IS continuable so we exercise the post-gate
	// missing-task path; an empty Task field falls through to the
	// "cannot inherit" branch.
	_ = fx.createPrevRun(t, prevID, StateKilledByUser, "")

	_, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
	if err == nil {
		t.Fatalf("PrepareContinuation: expected error, got nil")
	}
	if !strings.Contains(err.Error(), "no task to inherit") {
		t.Errorf("error message = %q, want substring 'no task to inherit'", err.Error())
	}
	// The runs dir must contain only the previous run (the new one was
	// rolled back).
	entries, err := os.ReadDir(RunsRoot(fx.aiEnvDir))
	if err != nil {
		t.Fatalf("read runs dir: %v", err)
	}
	if len(entries) != 1 || entries[0].Name() != prevID {
		t.Errorf("runs dir entries = %v, want only [%s]", entries, prevID)
	}
}

// TestPrepareContinuation_LinkedRunJSONRoundTrip exercises the
// integration between PrepareContinuation and the supervisor's
// run.json writer. The helper returns a PreviousRunID; threading that
// through SupervisorOptions.LinkedPreviousRun (via LinkedPreviousRunPtr)
// and writing a Record must produce a run.json whose linked_previous_run
// field matches the predecessor. This is the on-disk link the plan's
// "records the previous run id in run.json" rule asks for.
func TestPrepareContinuation_LinkedRunJSONRoundTrip(t *testing.T) {
	fx := newContinueFixture(t)
	prevID := "20260528-101000-aa11bb"
	_ = fx.createPrevRun(t, prevID, StateTimedOut, "Resume me")

	cont, err := PrepareContinuation(fx.aiEnvDir, fx.envName, "", fx.now)
	if err != nil {
		t.Fatalf("PrepareContinuation: %v", err)
	}

	// Simulate the supervisor writing its first run.json snapshot. The
	// supervisor's writeRecordSnapshot serializes LinkedPreviousRun
	// straight into linked_previous_run; we mirror that here so the
	// test asserts the persisted bytes the supervisor would write.
	linked := LinkedPreviousRunPtr(cont.PreviousRunID)
	rec := Record{
		RunID:               cont.NewRun.ID,
		EnvName:             fx.envName,
		Agent:               "claude",
		Task:                cont.PreviousRecord.Task,
		State:               StateCreated,
		Backend:             "local-process",
		ModelCredentialMode: ModelCredentialBackendManaged,
		LinkedPreviousRun:   linked,
	}
	if err := WriteRecord(cont.NewRun.Path, rec); err != nil {
		t.Fatalf("WriteRecord: %v", err)
	}

	got, err := ReadRecord(cont.NewRun.Path)
	if err != nil {
		t.Fatalf("ReadRecord: %v", err)
	}
	if got.LinkedPreviousRun == nil {
		t.Fatalf("linked_previous_run = nil, want %q", prevID)
	}
	if *got.LinkedPreviousRun != prevID {
		t.Errorf("linked_previous_run = %q, want %q", *got.LinkedPreviousRun, prevID)
	}
}

// TestLinkedPreviousRunPtr verifies the helper's two cases: empty id
// returns nil (the supervisor's "no link" path); non-empty id returns
// a *string pointing at a copy. The copy semantics matter because the
// supervisor stores the pointer in SupervisorOptions and a future
// mutation of the source string must not leak into the snapshot.
func TestLinkedPreviousRunPtr(t *testing.T) {
	if got := LinkedPreviousRunPtr(""); got != nil {
		t.Errorf("LinkedPreviousRunPtr(\"\") = %v, want nil", got)
	}
	id := "20260528-100000-deadbe"
	ptr := LinkedPreviousRunPtr(id)
	if ptr == nil {
		t.Fatalf("LinkedPreviousRunPtr(%q) = nil, want non-nil", id)
	}
	if *ptr != id {
		t.Errorf("*LinkedPreviousRunPtr(%q) = %q, want %q", id, *ptr, id)
	}
	// Mutate the source variable to confirm the helper copied the value.
	id = "tampered"
	if *ptr != "20260528-100000-deadbe" {
		t.Errorf("*ptr = %q, want unchanged after source mutation", *ptr)
	}
}
